name: iata
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26
  - sed
  - grep
  - lynx
  - wget
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - umap-learn
  - hdbscan
  - spacy
  - nltk
  - tqdm
  - seaborn
  - pip
  - pip:
      - pdfminer.six
      - bertopic
      - sentence-transformers
      - "thinc<8.2.1"    # Prevents torch/Numpy2 dependency
      - pymupdf==1.25.5
      - kaleido
      - nbformat>=4.2.0
      - ipywidgets
      - faiss-cpu
      - transformers
      - torch
