name: iata
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26
  - spacy==3.5.4
  - thinc==8.1.10 # Prevents torch/Numpy2 dependency
  - sed
  - grep
  - lynx
  - wget
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - umap-learn
  - hdbscan
  - nltk
  - tqdm
  - seaborn
  - openai
  - pip
  - pip:
      - pdfminer.six
      - bertopic==0.16.4
      - sentence-transformers==2.2.2
      - pymupdf==1.25.5
      - kaleido
      - nbformat>=4.2.0
      - ipywidgets
      - faiss-cpu
      - transformers
      - torch
