# Hand-curated map of topic names to human-readable formats

custom_map = {
    "fuel_emissions_passenger_global": "Emissions",
    "safety_iosa_accidents_accident": "Safety",
    "security_information_smart_security_passenger": "Security",
    "settlement_billion_processed_bsp": "Settlement/BSP",
    "charges_airport_airports_infrastructure": "Airport Charges/Infrastructure",
    "global_governments_important_great": "Global Governments",
    "ndc_order_travel_retailing": "NDC",
    "baggage_fast_travel_fast_boarding": "Baggage",
    "cargo_e-freight_freight_e-awb": "Cargo & E-Freight",
    "saf_corsia_emissions_production": "SAF",
    "regulation_rights_passenger_rights_regulations": "Passenger Rights Regulations",
    "markets_growth_load_premium": "Markets Growth",
    "covid-19_health_testing_travel": "COVID‑19",
    "china_cargo_latam_express": "Emerging Economies",
    "tax_taxes_taxation_government": "Tax",
    "data_intelligence_consulting_cargois": "Data & AI",
    "training_itdi_strategic_courses": "Training",
    "emissions_carbon_environmental_technology": "Emissions",
    "profit_billion_net_profits": "Profit",
    "slot_wsg_slots_airport": "Airport Slots",
    "representing_group_klm_france": "Representing",
    "atm_airspace_european_nextgen": "Air Transport Market",
    "identity_id_digital_biometric": "Digital ID",
    "diversity_inclusion_diversity_inclusion_female": "Diversity & Inclusion",
    "ienva_waste_environmental_assessment": "IENVA",
    "fuel_jet_fuel_jet_supply": "Fuel",
    "oil_barrel_prices_fuel": "Oil Prices",
    "isago_ground_audits_audit": "ISAGO",
    "domestic_travel_rpks_international": "Domestic Travel",
    "unruly": "Unruly Passengers",
    "cargo_trade_growth_global": "Global Trade",
}